---
deployment:
  tasks:
    - export APP_DIR=/home/aimagics/public_html/anujdhanuka.aimagicsuite.com
    - cd $APP_DIR
    - /opt/cpanel/ea-nodejs20/bin/npm install --production
    - /opt/cpanel/ea-nodejs20/bin/npm run build
    - /usr/local/cpanel/scripts/restartsrv_httpd
